// autowire.cpp — libclang codegen tool: derive DI registrations from constructors.
//
// Parses a C++ header, finds each class's "injection constructor" — a public
// constructor whose parameters are all std::shared_ptr<T> — and emits a
// register_autowired(Container&) function full of bind_auto<T, Deps...>() calls.
// That removes the one remaining manual step of bind_auto: hand-listing the
// dependency types. The constructor signature becomes the single source of truth.
//
// Limitations (kept deliberately small):
//   - Only std::shared_ptr<T> parameters are treated as injectable.
//   - Picks the first public constructor that qualifies (no overload ranking).
//   - Emits bind_auto (transient) only. Lifetime (singleton vs transient) and
//     interface->implementation bindings can't be inferred from a constructor
//     signature and must still be declared by hand.
//
// Build needs libclang. Usage:
//   autowire <header> -o <out.cpp> [-- <extra clang args, e.g. -I include>]
//
#include <clang-c/Index.h>

#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace {

std::string take(CXString s) {
    const char* c = clang_getCString(s);
    std::string r = c ? c : "";
    clang_disposeString(s);
    return r;
}

struct Binding {
    std::string type;              // class to construct
    std::vector<std::string> deps; // shared_ptr<...> inner types, in order
};

struct ClassCtx {
    std::string class_name;
    bool found = false;     // already captured an injection ctor for this class?
    Binding binding;
};

// If `t` is std::shared_ptr<X>, return X's spelling; otherwise empty.
std::string shared_ptr_inner(CXType t) {
    std::string spelling = take(clang_getTypeSpelling(t));
    if (spelling.find("shared_ptr") == std::string::npos) return "";
    if (clang_Type_getNumTemplateArguments(t) < 1) return "";
    CXType arg = clang_Type_getTemplateArgumentAsType(t, 0);
    return take(clang_getTypeSpelling(arg));
}

// Visits the children of a class: looks for the first qualifying public ctor.
CXChildVisitResult visit_member(CXCursor c, CXCursor, CXClientData data) {
    auto& ctx = *static_cast<ClassCtx*>(data);
    if (ctx.found) return CXChildVisit_Continue;
    if (clang_getCursorKind(c) != CXCursor_Constructor) return CXChildVisit_Continue;
    if (clang_getCXXAccessSpecifier(c) != CX_CXXPublic) return CXChildVisit_Continue;

    int nargs = clang_Cursor_getNumArguments(c);
    if (nargs <= 0) return CXChildVisit_Continue; // no-dep ctors: nothing to wire

    std::vector<std::string> deps;
    bool all_injectable = true;
    for (int i = 0; i < nargs; ++i) {
        CXCursor parm = clang_Cursor_getArgument(c, static_cast<unsigned>(i));
        std::string inner = shared_ptr_inner(clang_getCursorType(parm));
        if (inner.empty()) { all_injectable = false; break; }
        deps.push_back(inner);
    }
    if (!all_injectable) return CXChildVisit_Continue;

    ctx.binding = Binding{ctx.class_name, std::move(deps)};
    ctx.found = true;
    return CXChildVisit_Break;
}

// Top-level visitor: finds class/struct definitions, recurses into each.
CXChildVisitResult visit_top(CXCursor c, CXCursor, CXClientData data) {
    auto& out = *static_cast<std::vector<Binding>*>(data);
    CXCursorKind k = clang_getCursorKind(c);
    if ((k == CXCursor_ClassDecl || k == CXCursor_StructDecl) &&
        clang_isCursorDefinition(c)) {
        ClassCtx ctx;
        ctx.class_name = take(clang_getCursorSpelling(c));
        if (!ctx.class_name.empty()) {
            clang_visitChildren(c, visit_member, &ctx);
            if (ctx.found) out.push_back(std::move(ctx.binding));
        }
    }
    return CXChildVisit_Recurse; // descend into namespaces too
}

void emit(std::ostream& os, const std::string& header,
          const std::vector<Binding>& bindings) {
    // Include by basename, resolved via the build's include dirs — matches how the
    // project's own sources include each other (e.g. #include "user_controller.hpp").
    std::string basename = header.substr(header.find_last_of("/\\") + 1);
    os << "// GENERATED by tools/autowire — do not edit.\n"
       << "// Source header: " << header << "\n"
       << "#include \"container.hpp\"\n"
       << "#include \"" << basename << "\"\n\n"
       << "void register_autowired(Container& container) {\n";
    if (bindings.empty()) {
        os << "    // (no injection constructors found)\n";
    }
    for (const auto& b : bindings) {
        os << "    container.bind_auto<" << b.type;
        for (const auto& d : b.deps) os << ", " << d;
        os << ">();\n";
    }
    os << "}\n";
}

} // namespace

int main(int argc, char** argv) {
    std::string header;
    std::string out_path; // empty => stdout
    std::vector<const char*> clang_args;
    bool past_sep = false;
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (past_sep) { clang_args.push_back(argv[i]); continue; }
        if (a == "--") { past_sep = true; }
        else if (a == "-o" && i + 1 < argc) { out_path = argv[++i]; }
        else if (header.empty()) { header = a; }
    }
    if (header.empty()) {
        std::cerr << "usage: autowire <header> -o <out.cpp> [-- <clang args>]\n";
        return 2;
    }

    // Parse as C++20 so std:: types resolve the same way the framework builds.
    std::vector<const char*> args = {"-std=c++20", "-x", "c++"};
    args.insert(args.end(), clang_args.begin(), clang_args.end());

    CXIndex index = clang_createIndex(/*excludeDeclarations=*/0, /*display=*/0);
    CXTranslationUnit tu = clang_parseTranslationUnit(
        index, header.c_str(), args.data(), static_cast<int>(args.size()),
        nullptr, 0, CXTranslationUnit_None);
    if (!tu) {
        std::cerr << "autowire: failed to parse " << header << "\n";
        clang_disposeIndex(index);
        return 1;
    }

    // Surface fatal diagnostics (missing includes etc.) but don't hard-fail on
    // warnings — partial ASTs are still useful for a spike.
    unsigned ndiag = clang_getNumDiagnostics(tu);
    for (unsigned i = 0; i < ndiag; ++i) {
        CXDiagnostic d = clang_getDiagnostic(tu, i);
        if (clang_getDiagnosticSeverity(d) >= CXDiagnostic_Error)
            std::cerr << "autowire: " << take(clang_formatDiagnostic(d, 0)) << "\n";
        clang_disposeDiagnostic(d);
    }

    std::vector<Binding> bindings;
    clang_visitChildren(clang_getTranslationUnitCursor(tu), visit_top, &bindings);

    if (out_path.empty()) {
        emit(std::cout, header, bindings);
    } else {
        std::ofstream f(out_path);
        if (!f) { std::cerr << "autowire: cannot write " << out_path << "\n"; return 1; }
        emit(f, header, bindings);
        std::cerr << "autowire: wrote " << bindings.size() << " binding(s) to "
                  << out_path << "\n";
    }

    clang_disposeTranslationUnit(tu);
    clang_disposeIndex(index);
    return 0;
}
