// demo_driver.cpp — proves genmodel output compiles and works end to end.
// Uses WidgetRepository, which exists only in the generated mapper header.
#include <cstdio>
#include <memory>

#include "database.hpp"
#include "widget.gen.hpp" // generated by genmodel from demo_model.hpp

int main() {
    WidgetRepository repo(std::make_shared<MemoryConnection>());

    Widget w{0, "generated", true, 5};
    repo.insert(w);

    auto got = repo.find(w.id);
    auto active = repo.query().where("active", Value{true}).get();

    bool ok = w.id > 0 && got.has_value() && got->name == "generated" && got->quantity == 5 &&
              active.size() == 1;
    std::printf("codegen_demo: id=%lld ok=%d\n", static_cast<long long>(w.id), ok ? 1 : 0);
    return ok ? 0 : 1;
}
