// genmodel.cpp — model-mapper codegen.
//
// Reads a header, finds each plain model struct (one with an `id` field), and emits
// the mechanical Mapper + Repository<T, Mapper> alias we otherwise hand-write — the
// boilerplate is ~24 lines/model. The struct becomes the single
// source of truth; add a field, regenerate, done.
//
// Constraints (spike scope): fields must be Value-compatible (std::int64_t / double /
// std::string / bool); a model is any struct with an `id` field. Build needs libclang.
//   genmodel <header> -o <out.hpp> [-- <clang args, e.g. -I include>]
#include <clang-c/Index.h>

#include <algorithm>
#include <cctype>
#include <fstream>
#include <iostream>
#include <string>
#include <utility>
#include <vector>

namespace {

std::string take(CXString s) {
    const char* c = clang_getCString(s);
    std::string r = c ? c : "";
    clang_disposeString(s);
    return r;
}

// std::string can spell as std::__cxx11::basic_string<...>; normalise it back.
std::string normalise_type(std::string spelling) {
    if (spelling.find("basic_string") != std::string::npos) return "std::string";
    return spelling;
}

std::string pluralise_lower(const std::string& name) {
    std::string out;
    for (char c : name) out += static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return out + "s";
}

struct Field {
    std::string name;
    std::string type;
};
struct Model {
    std::string name;
    std::vector<Field> fields;
};

CXChildVisitResult visit_field(CXCursor c, CXCursor, CXClientData data) {
    if (clang_getCursorKind(c) == CXCursor_FieldDecl) {
        auto& m = *static_cast<Model*>(data);
        m.fields.push_back({take(clang_getCursorSpelling(c)),
                            normalise_type(take(clang_getTypeSpelling(clang_getCursorType(c))))});
    }
    return CXChildVisit_Continue;
}

CXChildVisitResult visit_top(CXCursor c, CXCursor, CXClientData data) {
    CXCursorKind k = clang_getCursorKind(c);
    if ((k == CXCursor_StructDecl || k == CXCursor_ClassDecl) && clang_isCursorDefinition(c)) {
        Model m;
        m.name = take(clang_getCursorSpelling(c));
        clang_visitChildren(c, visit_field, &m);
        bool has_id = std::any_of(m.fields.begin(), m.fields.end(),
                                  [](const Field& f) { return f.name == "id"; });
        if (!m.name.empty() && has_id)
            static_cast<std::vector<Model>*>(data)->push_back(std::move(m));
    }
    return CXChildVisit_Recurse;
}

void emit(std::ostream& os, const std::string& header, const std::vector<Model>& models) {
    std::string basename = header.substr(header.find_last_of("/\\") + 1);
    os << "// GENERATED by tools/codegen/genmodel — do not edit.\n"
       << "// Source header: " << header << "\n"
       << "#pragma once\n"
       << "#include \"database.hpp\"\n"
       << "#include \"repository.hpp\"\n"
       << "#include \"" << basename << "\"\n";
    for (const auto& m : models) {
        os << "\nstruct " << m.name << "Mapper {\n"
           << "    static std::string table() { return \"" << pluralise_lower(m.name) << "\"; }\n\n"
           << "    static " << m.name << " hydrate(const Row& r) {\n"
           << "        return " << m.name << "{\n";
        for (const auto& f : m.fields)
            os << "            r.get<" << f.type << ">(\"" << f.name << "\"),\n";
        os << "        };\n    }\n\n"
           << "    static Row to_row(const " << m.name << "& m) {\n        Row r;\n";
        for (const auto& f : m.fields)
            os << "        r.set(\"" << f.name << "\", m." << f.name << ");\n";
        os << "        return r;\n    }\n\n"
           << "    static std::int64_t id(const " << m.name << "& m) { return m.id; }\n"
           << "    static void set_id(" << m.name << "& m, std::int64_t id) { m.id = id; }\n"
           << "};\n\n"
           << "using " << m.name << "Repository = Repository<" << m.name << ", " << m.name
           << "Mapper>;\n";
    }
}

} // namespace

int main(int argc, char** argv) {
    std::string header, out_path;
    std::vector<const char*> clang_args;
    bool past_sep = false;
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (past_sep) { clang_args.push_back(argv[i]); }
        else if (a == "--") { past_sep = true; }
        else if (a == "-o" && i + 1 < argc) { out_path = argv[++i]; }
        else if (header.empty()) { header = a; }
    }
    if (header.empty()) {
        std::cerr << "usage: genmodel <header> -o <out.hpp> [-- <clang args>]\n";
        return 2;
    }

    std::vector<const char*> args = {"-std=c++20", "-x", "c++"};
    args.insert(args.end(), clang_args.begin(), clang_args.end());

    CXIndex index = clang_createIndex(0, 0);
    CXTranslationUnit tu = clang_parseTranslationUnit(index, header.c_str(), args.data(),
                                                      static_cast<int>(args.size()), nullptr, 0,
                                                      CXTranslationUnit_None);
    if (!tu) {
        std::cerr << "genmodel: failed to parse " << header << "\n";
        clang_disposeIndex(index);
        return 1;
    }

    std::vector<Model> models;
    clang_visitChildren(clang_getTranslationUnitCursor(tu), visit_top, &models);

    if (out_path.empty()) {
        emit(std::cout, header, models);
    } else {
        std::ofstream f(out_path);
        emit(f, header, models);
        std::cerr << "genmodel: wrote " << models.size() << " mapper(s) to " << out_path << "\n";
    }

    clang_disposeTranslationUnit(tu);
    clang_disposeIndex(index);
    return 0;
}
