// generators.hpp — cpp-artisan make:* scaffolding (template-based, no libclang).
// Rendering is pure (unit-tested in test_generators); the artisan command just
// writes the rendered string to a new file.
#pragma once
#include <cctype>
#include <filesystem>
#include <fstream>
#include <string>

inline std::string to_snake(const std::string& s) {
    std::string out;
    for (std::size_t i = 0; i < s.size(); ++i) {
        char c = s[i];
        if (std::isupper(static_cast<unsigned char>(c))) {
            if (i > 0) out += '_';
            out += static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        } else {
            out += c;
        }
    }
    return out;
}

inline std::string table_name(const std::string& pascal) { return to_snake(pascal) + "s"; }

// A model: plain struct + hand-written-style mapper + repository alias (same shape
// the codegen tool emits — make:model is the quick-start, genmodel is the bulk tool).
inline std::string render_model(const std::string& name) {
    const std::string t = table_name(name);
    return "// " + to_snake(name) +
           ".hpp — generated by cpp-artisan make:model\n"
           "#pragma once\n"
           "#include <cstdint>\n"
           "#include <string>\n\n"
           "#include \"database.hpp\"\n"
           "#include \"repository.hpp\"\n\n"
           "struct " + name + " {\n"
           "    std::int64_t id = 0;\n"
           "    std::string name;\n"
           "};\n\n"
           "struct " + name + "Mapper {\n"
           "    static std::string table() { return \"" + t + "\"; }\n\n"
           "    static " + name + " hydrate(const Row& r) {\n"
           "        return " + name + "{\n"
           "            r.get<std::int64_t>(\"id\"),\n"
           "            r.get<std::string>(\"name\"),\n"
           "        };\n"
           "    }\n\n"
           "    static Row to_row(const " + name + "& m) {\n"
           "        Row r;\n"
           "        r.set(\"id\", m.id);\n"
           "        r.set(\"name\", m.name);\n"
           "        return r;\n"
           "    }\n\n"
           "    static std::int64_t id(const " + name + "& m) { return m.id; }\n"
           "    static void set_id(" + name + "& m, std::int64_t id) { m.id = id; }\n"
           "};\n\n"
           "using " + name + "Repository = Repository<" + name + ", " + name + "Mapper>;\n";
}

// A migration skeleton (Laravel: database/migrations/*). The table + columns are
// left as a TODO for the developer to fill in.
inline std::string render_migration(const std::string& name) {
    const std::string snake = to_snake(name);
    return "// " + snake +
           ".hpp — generated by cpp-artisan make:migration\n"
           "#pragma once\n"
           "#include \"migration.hpp\"\n"
           "#include \"schema.hpp\"\n\n"
           "struct " + name + " : Migration {\n"
           "    std::string name() const override { return \"0001_" + snake + "\"; }\n\n"
           "    void up(Connection& c) override {\n"
           "        Schema::create(c, \"table_name\", [](Blueprint& t) {\n"
           "            t.id();\n"
           "            // t.string(\"title\");\n"
           "            // t.integer(\"count\");\n"
           "            // t.boolean(\"active\");\n"
           "        });\n"
           "    }\n\n"
           "    void down(Connection& c) override { Schema::drop_if_exists(c, \"table_name\"); }\n"
           "};\n";
}

// A controller skeleton with the usual REST actions.
inline std::string render_controller(const std::string& name) {
    return "// " + to_snake(name) +
           "_controller.hpp — generated by cpp-artisan make:controller\n"
           "#pragma once\n"
           "#include \"http.hpp\"\n\n"
           "class " + name + "Controller {\n"
           "public:\n"
           "    Response index(Request&) { return Response::json(\"[]\"); }\n"
           "    Response show(Request& req) { (void)req; return Response::json(\"{}\"); }\n"
           "    Response store(Request& req) { (void)req; return Response::json(\"{}\", 201); }\n"
           "};\n";
}

// Write content to a new file; refuses to overwrite. Returns false + sets err on failure.
inline bool write_new_file(const std::string& path, const std::string& content, std::string& err) {
    namespace fs = std::filesystem;
    if (fs::exists(path)) {
        err = "already exists: " + path;
        return false;
    }
    fs::path p(path);
    if (p.has_parent_path()) fs::create_directories(p.parent_path());
    std::ofstream f(path);
    if (!f) {
        err = "cannot write: " + path;
        return false;
    }
    f << content;
    return true;
}
